### ISSUE TITLE
Trouble in receiving throttle, brake and steering

### ISSUE THREAD

**Issue by Sophistt** [cpgeier/DeepGTAV_Tools#2]
Hi, I use VPilot to receive the messages to from DeepGTAV as you said, but it seems some problems happen when I receive the message. I can get the correct data such as 'frame', 'speed', 'reward' and so on, but the data of 'throttle', 'brake' and 'steering' do not reflect correctly, which is always keeping as 0 or 1. Does the game version or driving mode influence this?

**Comment by cpgeier** [comment]
Does the in-game AI drive correctly, or are you using manual driving?

**Comment by Sophistt** [comment]
@cpgeier Thanks， the in_game AI drives correctly, and I find that the inconsistent version results this problem. Now I solve this problem by changing the game version.
