### ISSUE TITLE
Location of model_trained_categorical.h5 pretrained weights

### ISSUE THREAD

**Issue by ctargon** [cpgeier/DeepGTAV_Tools#3]
The drive_categorical.py file loads a pretrained model which is not provided in the repo. Is there a place we can find these weights?

**Comment by cpgeier** [comment]
Just changed drive_categorical.py to include sample_model.h5. I added sample_model.h5 awhile ago on the repo, but it looks like a ran out of bandwidth on the GitHub LFS. I am going to look into putting the sample_model.h5 on Google Drive.

**Comment by Raj800** [comment]
Hey,  can you share the link to the model.h5 file?
I am not able to find it in the repo.
