### ISSUE TITLE
Git LFS: (0 of 1 files) 0 B / 262.27 MB .batch response: This repository is over its data quota. Purchase more data packs to restore access.

### ISSUE THREAD

**Issue by stulin** [cpgeier/DeepGTAV_Tools#7]
Hi:
I'd like to git clone the folder and I met the problem as following:

D:\Git LFS\1>git lfs clone https://github.com/cpgeier/SantosNet.git
WARNING: 'git lfs clone' is deprecated and will not be updated
          with new flags from 'git clone'
'git clone' has been updated in upstream Git to have comparable
speeds to 'git lfs clone'.
Cloning into 'SantosNet'...
remote: Enumerating objects: 79, done.
remote: Total 79 (delta 0), reused 0 (delta 0), pack-reused 79
Unpacking objects: 100% (79/79), done.
Git LFS: (0 of 1 files) 0 B / 262.27 MB
batch response: This repository is over its data quota. Purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/cpgeier/SantosNet.git/info/lfs'

would you like to purchase more data packs and restore access, thanks very much!

**Comment by cpgeier** [comment]
Removed file and added model hosted on Google Drive, check readme for sample model link
